package Test.Bean;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class AC01Bean {
    private String a_rid;
    private Long aac001;
    private String aaz177;
    private String aac003;
    private String aac058;
    private String aac147;
    private String aac004;
    private String aac006;
    private String cac001;
    private String cae457;
    private String cac220;
    private String aac005;
    private String aac007;
    private String aac017;
    private String aac024;
    private String aac020;
    private String aac009;
    private String aac002;
    private String cac222;
    private String aac012;
    private String cac221;
    private String aac028;
    private String cac205;
    private String aaf013;
    private String aac010;
    private String cac209;
    private String cac217;
    private String cac218;
    private String cac219;
    private String aae006;
    private String aae007;
    private String aae005;
    private String aae321;
    private String aae159;
    private String aac011;
    private String aac015;
    private String aac184;
    private String aac183;
    private String aac014;
    private String aac185;
    private String aac033;
    private String ala040;
    private String alc060;
    private String aae004;
    private String cac210;
    private String cac216;
    private String aac008;
    private String aac084;
    private String aac114;
    private String aac060;
    private String cae226;
    private String aae013;
    private String aac001_varchar;
    private String seqlogid;
    private String aaz001;
    private String aab001;
    private String aab301;
    private String zab001;
    private String fromtable;
    private String tempaccount;
    private String aae138;
    private String yxjb;
    private String zone1;
    private String aac022;
    private String aca111;
    private String aca200;
    private String aca202;
    private String aca201;
    private String aca203;
    private String aca204;
    private String aca206;
    private String aca205;
    private String aca207;
    private String aae461;
    private String aac001qd;
    private String aaz177qd;
}
